import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 */
class MyTask extends DefaultTask {

    String to
    String content

    @TaskAction
    def send() {
        println "Sending to $to"
        println "Content: $content"
    }
}
